// <auto-generated />
namespace Company.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_));
        
        string IMigrationMetadata.Id
        {
            get { return "201612121359177__"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
